const dataAnalisa = [
  {
    parentId: 1,
    parent: 'Partisipasi Anggota dalam BMT',
    child: [
      {
        parentId: 1,
        id: 1,
        idChild: 1,
        keterangan: 'Menjadi anggota BMT sudah lebih dari tiga bulan',
        scores: 10,
      },
      {
        parentId: 1,
        id: 2,
        idChild: 2,
        keterangan: 'Menabung secara teratur dan terus menerus',
        scores: 10,
      },
      {
        parentId: 1,
        id: 3,
        idChild: 3,
        keterangan: 'Membayar pinjaman (yang lalu) secara disiplin',
        scores: 10,
      },
      {
        parentId: 1,
        id: 4,
        idChild: 4,
        keterangan: 'Selalu hadir dalam pertemuan anggota',
        scores: 10,
      },
      {
        parentId: 1,
        id: 5,
        idChild: 5,
        keterangan: 'Mudah bekerjasama dengan anggota yang lain',
        scores: 10,
      },
      {
        parentId: 1,
        id: 6,
        idChild: 6,
        keterangan: 'Berusaha menyumbangkan pikirannya bagi kemajuan BMT',
        scores: 10,
      },
      {
        parentId: 1,
        id: 7,
        idChild: 7,
        keterangan: 'Memiliki kesetiakawanan yang tinggi',
        scores: 10,
      },
      {
        parentId: 1,
        id: 8,
        idChild: 8,
        keterangan: 'Dikenal dengan baik oleh anggota BMT',
        scores: 10,
      },
    ],
  },
  {
    parentId: 2,
    parent: 'Kelayakan Usaha Anggota BMT',
    child: [
      {
        parentId: 1,
        id: 1,
        idChild: 9,
        keterangan: 'Usaha ini merupakan sumber mata pencahariaan pokok',
        scores: 10,
      },
      {
        parentId: 1,
        id: 2,
        idChild: 10,
        keterangan: 'Telah memiliki pengalaman berusaha',
        scores: 10,
      },
      {
        parentId: 1,
        id: 3,
        idChild: 11,
        keterangan: 'Sumber dagangan/bahan baku dan bahan penolong yang mudah diperoleh',
        scores: 10,
      },
      {
        parentId: 1,
        id: 4,
        idChild: 12,
        keterangan: 'Prospek pemasaran bagus dan masih dapat diperluas',
        scores: 10,
      },
      {
        parentId: 1,
        id: 5,
        idChild: 13,
        keterangan: 'Telah memiliki langganan yang tetap',
        scores: 10,
      },
      {
        parentId: 1,
        id: 6,
        idChild: 14,
        keterangan: 'Jumlah usaha yang sejenis belum terlalu banyak',
        scores: 10,
      },
      {
        parentId: 1,
        id: 7,
        idChild: 15,
        keterangan: 'Manajemen usaha secara tekun dan sungguh-sungguh',
        scores: 10,
      },
      {
        parentId: 1,
        id: 8,
        idChild: 16,
        keterangan: 'Jumlah omzet penjualan per-periode stabil atau meningkat',
        scores: 10,
      },
      {
        parentId: 1,
        id: 9,
        idChild: 17,
        keterangan: 'Tingkat keuntungan usaha diatas 50 % dari omzet penjulan per-bulan',
        scores: 10,
      },
      {
        parentId: 1,
        id: 10,
        idChild: 18,
        keterangan: 'Administarasi usaha dilakukan dengan tertip',
        scores: 10,
      },
    ],
  },
  {
    parentId: 3,
    parent: 'Watak dan Kepribadian Anggota',
    child: [
      {
        parentId: 3,
        id: 1,
        idChild: 19,
        keterangan: 'Bersikap tenang dan terbuka dalam mendidkusikan permohonan pembiayaan',
        scores: 10,
      },
      {
        parentId: 3,
        id: 2,
        idChild: 20,
        keterangan: 'Keadaan rumah tangga rukun dan tenteram',
        scores: 10,
      },
      {
        parentId: 3,
        id: 3,
        idChild: 21,
        keterangan: 'Mempunyai nama baik di lingkungan kerja/tempat tinggalnya',
        scores: 10,
      },
      {
        parentId: 3,
        id: 4,
        idChild: 22,
        keterangan: 'Menunjukkan perkembangan dalam kehidupan sosial ekonomi',
        scores: 10,
      },
      {
        parentId: 3,
        id: 5,
        idChild: 23,
        keterangan: 'Jujur, disiplin dan selalu berusaha menepati janji (dari sumber orang lain)',
        scores: 10,
      },
    ],
  },
  {
    parentId: 4,
    parent: 'Kemampuan membayar Pembiayaan',
    child: [
      {
        parentId: 4,
        id: 1,
        idChild: 24,
        keterangan: 'Kewajiban angsuran minimal 30 % dari penghasilan/pendapatan per bulan',
        scores: 10,
      },
      {
        parentId: 4,
        id: 2,
        idChild: 25,
        keterangan: 'Jumlah hasil usaha lebih besar dari nilai pembayaran barang',
        scores: 10,
      },
      {
        parentId: 4,
        id: 3,
        idChild: 26,
        keterangan: 'Tingkat keuntungan usaha layak dibanding kewajiban membayar pembiayaan',
        scores: 10,
      },
    ],
  },
  {
    parentId: 5,
    parent: 'Jaminan/Pengaman Pembiayaan',
    child: [
      {
        parentId: 5,
        id: 1,
        idChild: 27,
        keterangan:
          'Suami/Istri bersedia ikut menandatangani dokumen perjanjian pembiayaan yang sah secara hukum',
        scores: 10,
      },
      {
        parentId: 5,
        id: 2,
        idChild: 28,
        keterangan: 'Memiliki jumlah tabungan yang cukup sebagai pelengkap jaminan',
        scores: 10,
      },
      {
        parentId: 5,
        id: 3,
        idChild: 29,
        keterangan:
          'Bersedia meningkatkan harta milik pribadi sebagai jaminan pembiayaan tambahan (bila perlu)',
        scores: 10,
      },
      {
        parentId: 5,
        id: 4,
        idChild: 30,
        keterangan: 'Nilai harta yang dijaminkan lebih besar dari nilai pembiayaan yang dijaminkan',
        scores: 10,
      },
      {
        parentId: 5,
        id: 5,
        idChild: 31,
        keterangan: 'Ada pihak yang menjamin keamanan pembiayaan (bila perlu)',
        scores: 10,
      },
      {
        parentId: 5,
        id: 6,
        idChild: 32,
        keterangan: 'Memiliki upaya pencegahan & penanggulangan resiko yang membahayakan usaha',
        scores: 10,
      },
    ],
  },
  {
    parentId: 6,
    parent: 'Modal Usaha dan Keuangan',
    child: [
      {
        parentId: 6,
        id: 1,
        idChild: 33,
        keterangan: 'Jumlah modal sendiri tidak kurang dari 30 % terhadap nilai pembiayaan',
        scores: 10,
      },
      {
        parentId: 6,
        id: 2,
        idChild: 34,
        keterangan: 'Modal sendiri ditempatkan secara aman dan produktif',
        scores: 10,
      },
      {
        parentId: 6,
        id: 3,
        idChild: 35,
        keterangan:
          'Tidak memiliki hutang dari sumber lain dalam jumlah yang akan mengganggu kemampuan bayar',
        scores: 10,
      },
    ],
  },
  {
    parentId: 7,
    parent: 'Keadaan Ekonomi/Lingkungan Usahan',
    child: [
      {
        parentId: 7,
        id: 1,
        idChild: 36,
        keterangan: 'Adat istiadat dan kebudayaan masyarakat setempat mendukung',
        scores: 10,
      },
      {
        parentId: 7,
        id: 2,
        idChild: 37,
        keterangan: 'Usaha tidak mengganggu kesehatan dan kelestarian lingkungan',
        scores: 10,
      },
    ],
  },
];
export default dataAnalisa;
